console.log("Aprendamos como instalar una app en un celular Android")
console.log("Vamos al menu y buscamos Play Store")
console.log("Donde esta la lupa buscamos la app que queremos instalar")
console.log("Una vez encontrada, le damos instalar")
console.log("Esperamos que la misma se instale")
console.log("Cuando nos aparezca la opcion Abrir")
console.log("La abrimos y listo")
console.log("A disfrutar de la misma")
console.log("Puede ser un juego")
console.log("Algun editor de fotos")
console.log("O lo que quieras disfrutar")
